branches:
    only:
        - Dev
        - master
image: Visual Studio 2017

configuration:
    - Debug

before_build:
    - cmake -DCMAKE_GENERATOR_PLATFORM=x64 -Bbuild

build:
    project: build/Pholos.sln
