branches:
    only:
        - cmake_feature
image: Visual Studio 2017

configuration:
    - Release
    - Debug

before_build:
    - cmake -DCMAKE_GENERATOR_PLATFORM=x64 -Bbuild

build:
    project: Pholos.sln
