branches:
    only:
        - Dev
        - master
image: 
  - Visual Studio 2017
  - Visual Studio 2019

plataform:
  - x64

configuration:
    - Debug
    - Release

before_build:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_GENERATOR_PLATFORM=x64 -DENABLE_TEST=ON

build_script:
    - cmake --build . --config %configuration%

test_script:
    - '%APPVEYOR_BUILD_FOLDER\Pholos\test\%CONFIGURATION%\Tests.exe'
