name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      # Install fmt
      - name: install fmt
        run: |
            git clone https://github.com/fmtlib/fmt $HOME/runner/work/fmt
            cd $HOME/runner/work/fmt
            mkdir build
            cd build
            cmake .. -DFMT_TEST=OFF
            cmake --build . --target install
        shell: cmd
        
      # Build
      - name: Build
        run: |
            mkdir build
            cd build
            cmake .. -DENABLE_TEST=OFF
            cmake --build . --config Debug
            
        shell: cmd
